#!/usr/bin/env python3

"""
This is a very cynical imitation of a Philosopher program. It detects
long tests and death timing tests specified in test_config.py and fails
only the long test
"""

import sys

if len(sys.argv) != 5:
    exit(-1)

if int(sys.argv[1]) == 4 or int(sys.argv[1]) == 5:
    # This is a long test
    print("000005 3 whatever")
    print("00042" + " 3 died")
    exit(0)


# This is death time test imitation
print("000005 3 whatever")

death_time = sys.argv[2]

print("000" + death_time + " 3 died")
